export const ANIMATOR_PAUSE_CONSECUTIVE_FRAMES = 10;
export const ANIMATOR_PAUSE_ZERO_VELOCITY = 1;
export const DEFAULT_SNAP_TENSION = 300;
export const DEFAULT_SNAP_DAMPING = 0.7;
export const DEFAULT_GRAVITY_FALLOF = 40;
export const DEFAULT_GRAVITY_STRENGTH = 400;